In [123]:
import numpy as np
import pandas as pd

import yaml
from yaml.loader import SafeLoader

In [124]:
def get_database():
    from pymongo import MongoClient

    # Provide the mongodb atlas url to connect python to mongodb using pymongo
    username= 'python-projeto-tbd'
    password= 'root2021'
    
    CONNECTION_STRING = f"mongodb+srv://{username}:{password}@clusterstetbd.jilds.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"

    # Create a connection using MongoClient. You can import MongoClient or use pymongo.MongoClient
    client = MongoClient(CONNECTION_STRING, tlsAllowInvalidCertificates=True)

    # Create the database for our example (we will use the same database throughout the tutorial
    return client

def dump_df2mongo(df, collection, create_collection=True):
    
    if create_collection:
        return collection.insert_many(df.to_dict("records"))
    else:
        return None

In [139]:
cfg

{'customers': 'data/olist_customers_dataset.csv',
 'geolocation': 'data/olist_geolocation_dataset.csv',
 'order_items': 'data/olist_order_items_dataset.csv',
 'order_payments': 'data/olist_order_payments_dataset.csv',
 'order_reviews': 'data/olist_order_reviews_dataset.csv',
 'orders': 'data/olist_orders_dataset.csv',
 'products': 'data/olist_products_dataset.csv',
 'sellers': 'data/olist_sellers_dataset.csv'}

In [169]:
order_customer = pd.read_csv('data/olist_orders_dataset.csv')
customers = pd.read_csv('data/olist_customers_dataset.csv')
order_reviews = pd.read_csv('data/olist_order_reviews_dataset.csv')

In [170]:
customers = customers
order = order_customer[['order_id','customer_id']]
order_reviews = order_reviews[['order_id','review_score','review_comment_message']].dropna()

In [175]:
df_cust = customers.merge(order,on='customer_id').merge(order_reviews, on='order_id', how='left')

In [187]:
order_items = pd.read_csv('data/olist_order_items_dataset.csv')

In [190]:
df = df_cust.merge(order_items,on='order_id')

In [191]:
products = pd.read_csv('data/olist_products_dataset.csv')

In [193]:
df = df.merge(products,on='product_id')

In [201]:
df.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'review_score',
       'review_comment_message', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='object')

In [217]:
df_grouped = pd.concat([df.groupby('customer_unique_id')['product_category_name'].apply(list),
            df.groupby('customer_unique_id')['customer_state'].apply(list),
            df.groupby('customer_unique_id')['review_comment_message'].apply(list),
            df.groupby('customer_unique_id')['seller_id'].apply(list),
            df.groupby('customer_unique_id')['price'].apply(list),
            df.groupby('customer_unique_id')['freight_value'].apply(list),
            df.groupby('customer_unique_id')['product_category_name'].apply(list)] ,axis=1).reset_index()

In [219]:
df_agg = df_grouped.merge(
    df[['customer_unique_id', 'customer_zip_code_prefix','customer_city','customer_state',
        'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm',
        'product_width_cm']],
    on='customer_unique_id')

In [220]:
collection.agg_customer_unique
dump_df2mongo(df_agg, collection, create_collection=True)

<ipython-input-124-6f9b30bb1cc9>:19: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  return collection.insert_many(df.to_dict("records"))

In [222]:
df_agg

,customer_unique_id,product_category_name,customer_state_x,review_comment_message,seller_id,price,freight_value,product_category_name,customer_zip_code_prefix,customer_city,customer_state_y,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,0000366f3b9a7992bf8c76cfdf3221e2,[cama_mesa_banho],[SP],"[Adorei a cortina, ficou linda na minha sala, ...",[da8622b14eb17ae2831f4ac5b9dab84a],[129.9],[12.0],[cama_mesa_banho],7787,cajamar,SP,1.0,1500.0,34.0,7.0,32.0
1,0000b849f77a49e4a4ce2b2a4ca5be3f,[beleza_saude],[SP],[nan],[138dbe45fc62f1e244378131a6801526],[18.9],[8.29],[beleza_saude],6053,osasco,SP,1.0,375.0,26.0,11.0,18.0
2,0000f46a3911fa3c0805444483337064,[papelaria],[SC],[nan],[3d871de0142ce09b7081e2b9d1733cb1],[69.0],[17.22],[papelaria],88115,sao jose,SC,3.0,1500.0,25.0,50.0,35.0
3,0000f6ccb0745a6a4b88665a16c9f078,[telefonia],[PA],[Bom vendedor],[ef506c96320abeedfb894c34db06f478],[25.99],[17.63],[telefonia],66812,belem,PA,5.0,150.0,19.0,5.0,11.0
4,0004aac84e0df4da2b147fca70cf8255,[telefonia],[SP],[nan],[70a12e78e608ac31179aea7f8422044b],[180.0],[16.89],[telefonia],18040,sorocaba,SP,3.0,6050.0,16.0,3.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112822,fffcf5a5ff07b0908bd4e2dbc735a684,"[beleza_saude, beleza_saude]","[PE, PE]","[nan, nan]","[17f51e7198701186712e53a39c564617, 17f51e71987...","[680.0, 890.0]","[239.14, 258.28]","[beleza_saude, beleza_saude]",55250,sanharo,PE,1.0,30000.0,55.0,75.0,61.0
112823,fffea47cd6d3cc0a88bd621562a9d061,[bebes],[BA],[nan],[7aa4334be125fcdd2ba64b3180029f14],[64.89],[19.69],[bebes],44054,feira de santana,BA,2.0,1720.0,33.0,36.0,27.0
112824,ffff371b4d645b6ecea244b27531430a,[automotivo],[MT],[nan],[54aa8463e87776b5612f4bdc4bd5d4de],[89.9],[22.56],[automotivo],78552,sinop,MT,5.0,600.0,17.0,15.0,13.0
112825,ffff5962728ec6157033ef9805bacc48,[relogios_presentes],[ES],"[excelente lojas, a posterior vou fazer uma aq...",[7d13fca15225358621be4086e1eb0964],[115.0],[18.69],[relogios_presentes],29460,bom jesus do norte,ES,3.0,444.0,20.0,14.0,16.0
112826,ffffd2657e2aad2907e67c3e9daecbeb,[perfumaria],[PR],[nan],[cc419e0650a3c5ba77189a1882b7556a],[56.99],[14.57],[perfumaria],83608,campo largo,PR,2.0,400.0,18.0,11.0,11.0

In [221]:
df_agg.to_csv('data/df_agg_unique_customer.csv')